# Generated by Django 2.2.4 on 2021-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('pub_time', models.TimeField(verbose_name='time_published')),
                ('extra_text', models.CharField(max_length=250)),
            ],
        ),
    ]
